[package]
name = "wire"
version = "0.1.0"
authors = ["Henry Zimmerman <zimhen7@gmail.com>"]
edition = "2018"

[dependencies]
apply = "0.2.2"
serde = {version="1.0.85", features=["derive"]}
serde_json = "1.0.37"
