# Use postgres/example user/password credentials
version: '3.1'

services:

  db:
#    image: postgres:latest
    image: postgres:11
    restart: always
    environment:
      POSTGRES_PASSWORD: yeet
      POSTGRES_USER: yeet
      POSTGRES_DB: web_engineering

#  api:
#    image: yeet
#    restart: always
#    ports:
#      - 80:80
#    depends_on:
#      - db
#      - migration

  migration:
#    image: yeet
    build: .
    command: diesel migration run --migration-dir $HOME/backend/db --database-url postgres://yeet:yeet@db:5432/web_engineering
#    command: bash -c "./wait-for-it.sh db:5432 -q -- diesel migration run --migration-dir $HOME/backend/db --database-url postgres://yeet:yeet@db:5432/web_engineering"
    depends_on:
      - db
