version: "3"

services:
#  web:
#    build: ./web
#    volumes:
#      - ./web:/usr/src/app
#    ports:
#      - "3000:3000"
#    command: bash -c "npm && npm start"
#    links:
#      - api_server

  backend:
    build: ./backend
    ports: 
      - "8080:8080"
    volumes:
      - ./backend:/usr/src/app
    links:
      - db
    environment:
      DATABASE_URL: 'postgres://user:example@db:5432/web_engineering'
      TEST_DATABASE_URL: 'postgres://user:example@db:5432/web_engineering_test'
      TEST_DATABASE_NAME: 'web_engineering_test'
      DROP_DATABASE_URL: 'postgres://user:example@db:5432/postgres'

    # diesel infer_schema macro gives warnings with this flag.
    # environment:
    #   - CARGO_INCREMENTAL=1
    command: bash -c "bash ./wait_for_it.sh db:5432 -q -- diesel setup --migration-dir db/migrations && cargo watch -x run"
#    command: bash -c "bash ./wait_for_it.sh db:5432 -q -- cargo watch -x run"

  db:
    image: "postgres:latest"
    ports: 
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: example
      POSTGRES_USER: user
      POSTGRES_DB: web_engineering
      PGDATA: /var/lib/postgresql/data/pgdata

# cargo will try to redownload packages @ docker-compose up so store them here.
volumes:
  pgdata: {}
